### ISSUE TITLE
Introdução ao documento de arquitetura

### ISSUE THREAD

**Issue by MatheusHenrickSantos** [fga-eps-mds/2022-1-Squad6#2]
# Descrição
Estudar o que é, a importância e como criar um documento de arquitetura.

# Tarefa

- [ ] Estudar sobre documento de arquitetura.
- [ ] Pesquisar modelos de documentos de arquitetura.

# Critérios de aceitação

- [ ] Compartilhar o aprendizado com o grupo.
- [ ] Colocar o modelo no git.

**Comment by hannanhunny01** [comment]
### Documento de Arquitetura
O documento de arquitetura de software fornece uma visão geral de arquitetura abrangente do sistema de software. Serve como um meio de comunicação entre o arquiteto de software e outros membros de equipe de projeto, com relação a decisões arquiteturalmente significativas tomadas sobre o projeto.


### **Tarefa**

- [ ] Estudar sobre documento de arquitetura.
- [ ]  Pesquisar modelos de documentos de arquitetura.
### Critérios de aceitação

- [ ]  Compartilhar o aprendizado com o grupo.
- [ ]  Colocar o modelo no git.


Os documento/documentos sobre "introdução ao documento de arquitetura" foram colocados na pasta Material_de_estudos para que o resto da equipe também possa estudar esse material.
