### ISSUE TITLE
Estudo sobre metodologia scrum

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/2022-1-Squad6#4]
# Descrição
Estudar como funciona a metodologia e os beneficios de ultilizar a mesma.

# Tarefa

- [x] Estudar sobre metodologia scrum.
- [x] Definir horários para as reuniões.

# Critérios de aceitação

- [x] Compartilhar o aprendizado com o grupo.
- [ ] E definir funções e horarios do grupo.

**Comment by hannanhunny01** [comment]
- [ ] Estudar sobre metodologia scrum.
- [ ] Definir horários para as reuniões.
- [ ] Compartilhar o aprendizado com o grupo.
